import React from 'react';
import { FONT_BODY } from '../../globalStyles';

export const styles: Record<string, React.CSSProperties> = {
  container: { display: 'flex', flexDirection: 'column', height: '100%', fontFamily: FONT_BODY, border: '1px solid #21262d', borderRadius: 0, overflow: 'hidden', backgroundColor: '#0d1117', position: 'relative' },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, padding: '10px 14px', borderBottom: '1px solid #30363d', backgroundColor: '#161b22' },
  headerLeft: { display: 'flex', flexDirection: 'column', gap: 3, minWidth: 0 },
  headerNameRow: { display: 'flex', alignItems: 'center', gap: 6 },
  headerName: { fontSize: 'clamp(12px, 1.3vw, 15px)', fontWeight: 600, color: '#e6edf3', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  verifiedBadge: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 16, height: 16, borderRadius: '50%', backgroundColor: 'rgba(35, 134, 54, 0.2)', color: '#3fb950', fontSize: 10, fontWeight: 700, flexShrink: 0 },
  headerSubRow: { display: 'flex', alignItems: 'center', gap: 8 },
  headerMemberCount: { fontSize: 12, color: '#8b949e' },
  infoButton: { width: 28, height: 28, borderRadius: '50%', border: '1px solid #30363d', backgroundColor: 'transparent', color: '#c9d1d9', fontSize: 14, fontWeight: 600, fontStyle: 'italic', fontFamily: 'inherit', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'border-color 0.15s, color 0.15s' },
  renameInput: { fontSize: 15, fontWeight: 600, color: '#e6edf3', backgroundColor: '#0d1117', border: '1px solid #58a6ff', borderRadius: 4, padding: '2px 6px', fontFamily: 'inherit', outline: 'none', width: '100%', maxWidth: 240 },
  encryptionBadge: { fontSize: 9, fontWeight: 700, padding: '2px 8px', borderRadius: 1, backgroundColor: 'rgba(63, 185, 80, 0.08)', color: '#3fb950', border: '2px solid rgba(63, 185, 80, 0.4)', textTransform: 'uppercase' as const, letterSpacing: '0.12em', boxShadow: '0 0 6px rgba(63,185,80,0.2), inset 0 0 4px rgba(63,185,80,0.08)', fontFamily: '"SF Mono", "Fira Code", "Cascadia Code", monospace' },
  roomLabel: { fontSize: 13, color: '#c9d1d9' },
  syncErrorIndicator: { display: 'flex', alignItems: 'center', gap: 6, padding: '4px 14px', backgroundColor: 'rgba(210, 153, 34, 0.08)', borderBottom: '1px solid rgba(210, 153, 34, 0.15)' },
  messageList: { flex: 1, overflowY: 'auto', padding: 12, display: 'flex', flexDirection: 'column', gap: 2, scrollBehavior: 'smooth' as const, WebkitOverflowScrolling: 'touch' as const },
  dateSeparator: { display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '16px 0 8px' },
  dateSeparatorLine: { display: 'none' as const },
  dateSeparatorText: { fontSize: 12, fontWeight: 600, color: '#8b949e', letterSpacing: '0.03em', flexShrink: 0, backgroundColor: 'rgba(33, 38, 45, 0.85)', padding: '4px 14px', borderRadius: 12, boxShadow: '0 1px 3px rgba(0,0,0,0.2)' },
  timeGap: { display: 'flex', justifyContent: 'center', margin: '8px 0 4px' },
  timeGapText: { fontSize: 10, color: '#8b949e', backgroundColor: '#161b22', padding: '2px 10px', borderRadius: 10 },
  emptyState: { textAlign: 'center', color: '#8b949e', marginTop: 40, fontSize: 14 },
  messageBubble: { maxWidth: 'clamp(180px, 65%, 480px)', minWidth: 80, padding: '10px 14px', borderRadius: 16, fontSize: 'clamp(13px, 1.4vw, 15px)', lineHeight: 1.5, wordBreak: 'break-word' as const, overflowWrap: 'break-word' as const, overflow: 'hidden' as const, transition: 'background-color 0.15s' },
  ownMessage: { backgroundColor: '#1B6EF3', color: '#ffffff' },
  otherMessage: { backgroundColor: '#2D333B', color: '#e6edf3' },
  errorMessage: { opacity: 0.7, borderLeft: '3px solid #f85149' },
  previousSessionMessage: { opacity: 0.6, borderLeft: '2px solid #484f58' },
  previousSessionInline: { display: 'inline-flex', alignItems: 'center', gap: 5, cursor: 'help' },
  previousSessionText: { fontStyle: 'italic', opacity: 0.85, fontSize: 13, color: '#8b949e' },
  previousSessionLock: { fontSize: 12, flexShrink: 0, marginTop: 0, opacity: 0.5, color: '#8b949e' },
  previousSessionInfoIcon: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 14, height: 14, borderRadius: '50%', border: '1px solid #484f58', fontSize: 9, fontWeight: 600, fontStyle: 'italic', color: '#8b949e', cursor: 'help', flexShrink: 0, lineHeight: 1 },
  previousSessionBlock: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, padding: '10px 16px', margin: '8px 0', backgroundColor: 'rgba(139, 148, 158, 0.06)', border: '1px solid rgba(139, 148, 158, 0.12)', borderRadius: 10 },
  previousSessionBlockInner: { display: 'flex', alignItems: 'center', gap: 6 },
  previousSessionBlockText: { fontSize: 13, color: '#8b949e', fontStyle: 'italic' },
  previousSessionLearnMore: { fontSize: 10, color: '#6e7681', fontStyle: 'italic' },
  optimisticSending: { opacity: 0.7 },
  optimisticFailed: { opacity: 0.8, backgroundColor: '#4a3040', borderRight: '3px solid #f85149' },
  senderName: { fontSize: 12, fontWeight: 700, marginBottom: 3, letterSpacing: '0.01em' },
  messageBody: { display: 'flex', alignItems: 'flex-start', gap: 3, overflowWrap: 'break-word' as const, wordBreak: 'break-word' as const },
  encryptionLock: { fontSize: 10, flexShrink: 0, marginTop: 2, opacity: 0.75, filter: 'drop-shadow(0 0 4px rgba(63,185,80,0.6)) drop-shadow(0 0 8px rgba(63,185,80,0.3))', color: '#3fb950' },
  encryptionWarning: { fontSize: 14, color: '#8b949e', flexShrink: 0, marginTop: -1 },
  decryptErrorInline: { display: 'inline-flex', alignItems: 'center', gap: 5, cursor: 'help' },
  errorText: { fontStyle: 'italic', opacity: 0.8, fontSize: 13, color: '#8b949e' },
  timestampRow: { display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 4, marginTop: 4 },
  timestamp: { fontSize: 11, opacity: 0.5, textAlign: 'right', color: 'inherit', letterSpacing: '0.02em' },
  statusIcon: { fontSize: 10, opacity: 0.6 },
  statusIconSent: { fontSize: 11, color: '#ffffff', opacity: 0.8 },
  statusIconFailed: { fontSize: 12, color: '#f85149' },
  retryInlineButton: { padding: '1px 6px', fontSize: 10, fontWeight: 600, backgroundColor: 'rgba(248, 81, 73, 0.2)', color: '#f85149', border: '1px solid rgba(248, 81, 73, 0.4)', borderRadius: 3, cursor: 'pointer', fontFamily: 'inherit', marginLeft: 2 },
  deletedText: { fontStyle: 'italic', color: '#8b949e', opacity: 0.7 },
  contextMenu: { position: 'fixed' as const, zIndex: 9999, backgroundColor: '#1c2128', border: '1px solid rgba(99, 110, 123, 0.25)', borderRadius: 12, boxShadow: '0 12px 32px rgba(0,0,0,0.5), 0 2px 8px rgba(0,0,0,0.3)', padding: 6, minWidth: 140, backdropFilter: 'blur(12px)', animation: 'frame-context-menu-in 0.15s ease-out' },
  contextMenuItem: { display: 'block', width: '100%', padding: '8px 14px', fontSize: 13, color: '#f85149', backgroundColor: 'transparent', border: 'none', borderRadius: 6, cursor: 'pointer', textAlign: 'left' as const, fontFamily: 'inherit', transition: 'background-color 0.12s' },
  expiredText: { fontStyle: 'italic', color: '#8b949e', opacity: 0.6 },
  leaveButton: { padding: '4px 10px', fontSize: 11, fontWeight: 600, backgroundColor: 'rgba(248, 81, 73, 0.1)', color: '#f85149', border: '1px solid rgba(248, 81, 73, 0.3)', borderRadius: 6, cursor: 'pointer', fontFamily: 'inherit' },
  disappearingButton: { padding: '4px 8px', fontSize: 10, fontWeight: 600, backgroundColor: 'transparent', color: '#8b949e', border: '1px solid #30363d', borderRadius: 6, cursor: 'pointer', fontFamily: 'inherit', whiteSpace: 'nowrap' as const },
  disappearingButtonActive: { backgroundColor: 'rgba(210, 153, 34, 0.15)', color: '#d29922', borderColor: '#d29922' },
  disappearingMenu: { position: 'absolute' as const, top: '100%', right: 0, marginTop: 4, backgroundColor: '#21262d', border: '1px solid #30363d', borderRadius: 8, boxShadow: '0 8px 24px rgba(0,0,0,0.4)', padding: 6, zIndex: 100, minWidth: 160 },
  disappearingMenuTitle: { fontSize: 11, fontWeight: 600, color: '#8b949e', padding: '4px 8px 6px', borderBottom: '1px solid #30363d', marginBottom: 4 },
  disappearingMenuItem: { display: 'block', width: '100%', padding: '6px 8px', fontSize: 12, color: '#c9d1d9', backgroundColor: 'transparent', border: 'none', borderRadius: 4, cursor: 'pointer', textAlign: 'left' as const, fontFamily: 'inherit' },
  viewOnceIcon: { fontSize: 12, flexShrink: 0, marginTop: 1, opacity: 0.7 },
  newMessagesPill: { position: 'absolute' as const, bottom: 80, left: '50%', transform: 'translateX(-50%)', padding: '8px 20px', fontSize: 13, fontWeight: 600, color: '#ffffff', backgroundColor: '#1B6EF3', border: 'none', borderRadius: 20, cursor: 'pointer', fontFamily: 'inherit', boxShadow: '0 4px 16px rgba(27,110,243,0.35)', zIndex: 10, transition: 'opacity 0.2s, transform 0.15s', letterSpacing: '0.02em' },
  typingIndicator: { display: 'none', alignItems: 'center', gap: 4, padding: '4px 8px', marginTop: 4, alignSelf: 'flex-start', minHeight: 20 },
  typingDot: { width: 6, height: 6, borderRadius: '50%', backgroundColor: '#484f58', animation: 'frame-typing-bounce 1.4s infinite ease-in-out' },
  welcomeContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '40px 24px', textAlign: 'center', flex: 1 },
  welcomeIconWrap: { marginBottom: 12, opacity: 0.7 },
  welcomeTitle: { fontSize: 15, fontWeight: 600, color: '#e6edf3', marginBottom: 8, maxWidth: 320, lineHeight: 1.4 },
  welcomeSubtitle: { fontSize: 13, color: '#8b949e', marginBottom: 12 },
  welcomeE2eeBadge: { display: 'inline-flex', alignItems: 'center', gap: 4, padding: '4px 10px', borderRadius: 2, backgroundColor: 'rgba(35, 134, 54, 0.08)', color: '#3fb950', fontSize: 11, fontWeight: 600, border: '1px solid rgba(63, 185, 80, 0.3)', letterSpacing: '0.06em', textTransform: 'uppercase' as const },
  reactionsRow: { display: 'flex', flexWrap: 'wrap' as const, gap: 4, marginTop: 4 },
  reactionBadge: { display: 'inline-flex', alignItems: 'center', gap: 3, padding: '2px 6px', fontSize: 12, borderRadius: 10, border: '1px solid #30363d', backgroundColor: 'rgba(33, 38, 45, 0.8)', color: '#c9d1d9', cursor: 'pointer', fontFamily: 'inherit', transition: 'border-color 0.15s, background-color 0.15s', lineHeight: 1.3 },
  reactionBadgeOwn: { borderColor: '#58a6ff', backgroundColor: 'rgba(88, 166, 255, 0.15)' },
  hoverActionButton: { width: 24, height: 24, borderRadius: 6, border: 'none', backgroundColor: 'transparent', color: '#8b949e', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, padding: 0, transition: 'color 0.15s, background-color 0.15s', fontFamily: 'inherit', lineHeight: 1 },
  reactionPicker: { position: 'fixed' as const, zIndex: 9999, display: 'flex', gap: 2, padding: '4px 6px', backgroundColor: '#1c2128', border: '1px solid rgba(99, 110, 123, 0.35)', borderRadius: 20, boxShadow: '0 8px 24px rgba(0,0,0,0.4)', backdropFilter: 'blur(12px)', animation: 'frame-context-menu-in 0.15s ease-out' },
  reactionPickerEmoji: { width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, backgroundColor: 'transparent', border: 'none', borderRadius: '50%', cursor: 'pointer', transition: 'background-color 0.12s, transform 0.12s', fontFamily: 'inherit' },
  readReceiptIcon: { fontSize: 12, color: 'rgba(255,255,255,0.5)', opacity: 0.9, marginLeft: 2 },
  forwardOverlay: { position: 'fixed' as const, top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', zIndex: 10000, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  forwardDialog: { backgroundColor: '#161b22', border: '1px solid #30363d', borderRadius: 12, width: 320, maxHeight: 420, display: 'flex', flexDirection: 'column' as const, boxShadow: '0 16px 48px rgba(0,0,0,0.5)', animation: 'frame-context-menu-in 0.15s ease-out', overflow: 'hidden' },
  forwardTitle: { fontSize: 15, fontWeight: 600, color: '#e6edf3', padding: '16px 16px 12px', borderBottom: '1px solid #30363d' },
  forwardList: { flex: 1, overflowY: 'auto' as const, padding: '4px 0' },
  forwardRoomItem: { display: 'flex', alignItems: 'center', gap: 10, width: '100%', padding: '10px 16px', backgroundColor: 'transparent', border: 'none', cursor: 'pointer', fontFamily: 'inherit', textAlign: 'left' as const, transition: 'background-color 0.12s' },
  forwardCancel: { padding: '10px', fontSize: 13, fontWeight: 600, color: '#8b949e', backgroundColor: 'transparent', border: 'none', borderTop: '1px solid #30363d', cursor: 'pointer', fontFamily: 'inherit', borderRadius: '0 0 12px 12px', transition: 'color 0.12s' },

  // ── Feature: Search within chat ──
  searchButton: { width: 28, height: 28, borderRadius: '50%', border: '1px solid #30363d', backgroundColor: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'border-color 0.15s' },
  searchBar: { display: 'flex', alignItems: 'center', gap: 8, padding: '6px 14px', borderBottom: '1px solid #30363d', backgroundColor: '#1c2128' },
  searchInput: { flex: 1, padding: '6px 8px', fontSize: 13, color: '#c9d1d9', backgroundColor: '#0d1117', border: '1px solid #30363d', borderRadius: 6, fontFamily: 'inherit', outline: 'none' },
  searchCloseButton: { background: 'none', border: 'none', color: '#8b949e', fontSize: 14, cursor: 'pointer', padding: '2px 6px', borderRadius: 4, lineHeight: 1, fontFamily: 'inherit', flexShrink: 0 },

  // ── Feature: Pinned messages ──
  pinnedBar: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, padding: '6px 14px', borderBottom: '1px solid #30363d', backgroundColor: 'rgba(210, 153, 34, 0.06)', cursor: 'pointer', transition: 'background-color 0.15s' },
  pinnedBarLeft: { display: 'flex', alignItems: 'center', gap: 8, flex: 1, overflow: 'hidden' },
  pinnedBarClose: { background: 'none', border: 'none', color: '#8b949e', fontSize: 12, cursor: 'pointer', padding: '2px 6px', borderRadius: 4, lineHeight: 1, fontFamily: 'inherit', flexShrink: 0 },

  // ── Feature: Unread divider ──
  unreadDivider: { display: 'flex', alignItems: 'center', gap: 12, margin: '12px 0 6px' },
  unreadDividerLine: { flex: 1, height: 1, backgroundColor: '#58a6ff' },
  unreadDividerText: { fontSize: 11, fontWeight: 600, color: '#58a6ff', flexShrink: 0, textTransform: 'uppercase' as const, letterSpacing: '0.05em' },
};
