import crypto from 'crypto';
import { buildMerkleTree, getMerkleRoot, generateMerkleProof } from '../../src/services/merkleTree';

// Helper: replicate the internal sha256/hashPair logic for verification
function sha256(data: string): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

function hashPair(left: string, right: string): string {
  return sha256(left + right);
}

/**
 * Verify a Merkle proof by walking the proof path from leaf to root.
 * This is the client-side verification that doesn't exist in the server module,
 * but is critical to test that proofs generated by the server are valid.
 */
function verifyMerkleProof(
  leafHash: string,
  proof: Array<{ position: 'left' | 'right'; hash: string }>,
  expectedRoot: string,
): boolean {
  let computed = leafHash;
  for (const node of proof) {
    if (node.position === 'left') {
      computed = hashPair(node.hash, computed);
    } else {
      computed = hashPair(computed, node.hash);
    }
  }
  return computed === expectedRoot;
}

// ── buildMerkleTree ──

describe('buildMerkleTree', () => {
  it('returns a single empty string for empty input', () => {
    const tree = buildMerkleTree([]);
    expect(tree).toEqual([['']]);
  });

  it('returns a single-layer tree for one leaf', () => {
    const leaf = sha256('key1');
    const tree = buildMerkleTree([leaf]);
    expect(tree.length).toBe(1);
    expect(tree[0]).toEqual([leaf]);
  });

  it('builds a two-leaf tree correctly', () => {
    const a = sha256('key1');
    const b = sha256('key2');
    const tree = buildMerkleTree([a, b]);

    expect(tree.length).toBe(2);
    expect(tree[0]).toEqual([a, b]);
    expect(tree[1]).toEqual([hashPair(a, b)]);
  });

  it('handles odd number of leaves by duplicating the last', () => {
    const a = sha256('key1');
    const b = sha256('key2');
    const c = sha256('key3');
    const tree = buildMerkleTree([a, b, c]);

    // Level 0: [a, b, c]
    expect(tree[0]).toEqual([a, b, c]);
    // Level 1: [H(a,b), H(c,c)]  (c is duplicated)
    expect(tree[1]).toEqual([hashPair(a, b), hashPair(c, c)]);
    // Level 2 (root): [H(H(a,b), H(c,c))]
    expect(tree[2]).toEqual([hashPair(hashPair(a, b), hashPair(c, c))]);
  });

  it('builds a four-leaf tree (power of 2)', () => {
    const leaves = ['a', 'b', 'c', 'd'].map(sha256);
    const tree = buildMerkleTree(leaves);

    expect(tree.length).toBe(3); // 4 leaves -> 2 internal -> 1 root
    expect(tree[2].length).toBe(1); // single root
  });

  it('handles a large tree (16 leaves)', () => {
    const leaves = Array.from({ length: 16 }, (_, i) => sha256(`key${i}`));
    const tree = buildMerkleTree(leaves);

    // log2(16) + 1 = 5 levels
    expect(tree.length).toBe(5);
    expect(tree[4].length).toBe(1);
  });
});

// ── getMerkleRoot ──

describe('getMerkleRoot', () => {
  it('returns empty string for empty leaves', () => {
    expect(getMerkleRoot([])).toBe('');
  });

  it('returns the leaf itself for a single leaf', () => {
    const leaf = sha256('only-key');
    expect(getMerkleRoot([leaf])).toBe(leaf);
  });

  it('returns H(a,b) for two leaves', () => {
    const a = sha256('k1');
    const b = sha256('k2');
    expect(getMerkleRoot([a, b])).toBe(hashPair(a, b));
  });

  it('is deterministic', () => {
    const leaves = ['x', 'y', 'z'].map(sha256);
    expect(getMerkleRoot(leaves)).toBe(getMerkleRoot(leaves));
  });

  it('changes when any leaf changes', () => {
    const leaves1 = ['a', 'b', 'c'].map(sha256);
    const leaves2 = ['a', 'b', 'd'].map(sha256);
    expect(getMerkleRoot(leaves1)).not.toBe(getMerkleRoot(leaves2));
  });
});

// ── generateMerkleProof ──

describe('generateMerkleProof', () => {
  it('throws for out-of-range index', () => {
    const leaves = [sha256('a')];
    expect(() => generateMerkleProof(leaves, -1)).toThrow('Leaf index out of range');
    expect(() => generateMerkleProof(leaves, 1)).toThrow('Leaf index out of range');
  });

  it('returns empty proof for single leaf', () => {
    const leaf = sha256('single');
    const proof = generateMerkleProof([leaf], 0);
    expect(proof).toEqual([]);
  });

  it('generates valid proof for first leaf (2 leaves)', () => {
    const a = sha256('first');
    const b = sha256('second');
    const leaves = [a, b];
    const root = getMerkleRoot(leaves);
    const proof = generateMerkleProof(leaves, 0);

    expect(proof.length).toBe(1);
    expect(proof[0].hash).toBe(b);
    expect(proof[0].position).toBe('right');
    expect(verifyMerkleProof(a, proof, root)).toBe(true);
  });

  it('generates valid proof for last leaf (2 leaves)', () => {
    const a = sha256('first');
    const b = sha256('second');
    const leaves = [a, b];
    const root = getMerkleRoot(leaves);
    const proof = generateMerkleProof(leaves, 1);

    expect(proof.length).toBe(1);
    expect(proof[0].hash).toBe(a);
    expect(proof[0].position).toBe('left');
    expect(verifyMerkleProof(b, proof, root)).toBe(true);
  });

  it('generates valid proof for middle leaf (4 leaves)', () => {
    const leaves = ['a', 'b', 'c', 'd'].map(sha256);
    const root = getMerkleRoot(leaves);

    for (let i = 0; i < leaves.length; i++) {
      const proof = generateMerkleProof(leaves, i);
      expect(verifyMerkleProof(leaves[i], proof, root)).toBe(true);
    }
  });

  it('generates valid proof for odd-count tree', () => {
    const leaves = ['x', 'y', 'z'].map(sha256);
    const root = getMerkleRoot(leaves);

    for (let i = 0; i < leaves.length; i++) {
      const proof = generateMerkleProof(leaves, i);
      expect(verifyMerkleProof(leaves[i], proof, root)).toBe(true);
    }
  });

  it('generates valid proofs for large tree (15 leaves)', () => {
    const leaves = Array.from({ length: 15 }, (_, i) => sha256(`key-${i}`));
    const root = getMerkleRoot(leaves);

    // Verify proof for every leaf
    for (let i = 0; i < leaves.length; i++) {
      const proof = generateMerkleProof(leaves, i);
      expect(verifyMerkleProof(leaves[i], proof, root)).toBe(true);
    }
  });
});

// ── Proof verification edge cases ──

describe('Merkle proof verification', () => {
  it('fails when leaf is tampered', () => {
    const leaves = ['a', 'b', 'c', 'd'].map(sha256);
    const root = getMerkleRoot(leaves);
    const proof = generateMerkleProof(leaves, 0);

    const tamperedLeaf = sha256('tampered');
    expect(verifyMerkleProof(tamperedLeaf, proof, root)).toBe(false);
  });

  it('fails when proof node is tampered', () => {
    const leaves = ['a', 'b', 'c', 'd'].map(sha256);
    const root = getMerkleRoot(leaves);
    const proof = generateMerkleProof(leaves, 0);

    const tamperedProof = [...proof];
    tamperedProof[0] = { ...tamperedProof[0], hash: sha256('wrong') };
    expect(verifyMerkleProof(leaves[0], tamperedProof, root)).toBe(false);
  });

  it('fails with wrong root', () => {
    const leaves = ['a', 'b', 'c', 'd'].map(sha256);
    const proof = generateMerkleProof(leaves, 0);

    const wrongRoot = sha256('totally-wrong-root');
    expect(verifyMerkleProof(leaves[0], proof, wrongRoot)).toBe(false);
  });

  it('fails when proof is for a different leaf index', () => {
    const leaves = ['a', 'b', 'c', 'd'].map(sha256);
    const root = getMerkleRoot(leaves);
    const proofForLeaf0 = generateMerkleProof(leaves, 0);

    // Use proof for leaf 0 but verify against leaf 1
    expect(verifyMerkleProof(leaves[1], proofForLeaf0, root)).toBe(false);
  });
});
